- name: Create control plane
  block:

    - name: Check if Kubernetes cluster is already initialized
      ansible.builtin.stat:
        path: /etc/kubernetes/admin.conf
      register: kubeadm_config
      changed_when: false

    - name: Initialize Kubernetes cluster on first master
      ansible.builtin.command: >
        kubeadm init
        --control-plane-endpoint {{ control_plane_endpoint }}
        --pod-network-cidr {{ pod_network_cidr }}
        {{ kubeadm_extra_args }}
      register: kubeadm_init
      changed_when: kubeadm_init.rc == 0
      when: not kubeadm_config.stat.exists

    - name: Copy kubeconfig to user
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: "{{ ansible_env.HOME }}/.kube/config"
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        mode: '0600'
        remote_src: true
      when: not kubeadm_config.stat.exists

    - name: Generate join command for HA masters
      ansible.builtin.command: kubeadm token create --print-join-command
      register: join_command
      changed_when: false
      when: not kubeadm_config.stat.exists
      become: true


    - name: Save join command as a fact
      ansible.builtin.set_fact:
        join_command: "{{ join_command.stdout }}"
      when: not kubeadm_config.stat.exists

    - name: Save locally
      ansible.builtin.copy:
        content: "{{ join_command }}"
        dest: /home/ubuntu_raj/DevOps-SRE/k8s-setup/kubeadm_join.sh
        mode: '0755'
      delegate_to: localhost
      when: join_command is defined
