- name: Ensure the system is updated before setup
  meta: flush_handlers
  notify: update-system

- name: Disable swap
  shell: |
    swapoff -a
    sed -i '/swap/d' /etc/fstab

- name: Load kernel modules
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter

- name: Load modules now
  shell: |
    modprobe overlay
    modprobe br_netfilter

- name: Set sysctl params
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1

- name: Apply sysctl
  command: sysctl --system

- name: Ensure CRB repo is enabled (needed for containerd)
  shell: yum config-manager --set-enabled crb

- name: Install containerd
  yum:
    name: containerd
    state: present
    enablerepo: crb
    disablerepo: kubernetes


- name: Configure containerd
  shell: |
    mkdir -p /etc/containerd
    containerd config default > /etc/containerd/config.toml

- name: Restart containerd
  systemd:
    name: containerd
    state: restarted
    enabled: true

- name: Add Kubernetes repo
  copy:
    dest: /etc/yum.repos.d/kubernetes.repo
    content: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://pkgs.k8s.io/core:/stable:/v1.35/rpm/
      enabled=1
      gpgcheck=1
      gpgkey=https://pkgs.k8s.io/core:/stable:/v1.35/rpm/repodata/repomd.xml.key
      exclude=kubelet kubeadm kubectl cri-tools kubernetes-cni  
- name: Install Kubernetes packages
  yum:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    disable_excludes: kubernetes

- name: Enable kubelet
  systemd:
    name: kubelet
    enabled: true
