[masters]
master-init ansible_host=100.0.105.218 ansible_user=root ansible_port=2224

; master2     ansible_host=100.0.100.2 ansible_user=root
; master3     ansible_host=100.0.100.3 ansible_user=root

[workers]
web1 ansible_host=192.168.1.11 ansible_user=root ansible_port=2222
; web1 ansible_host=10.0.2.200 ansible_user=root

# [all_nodes:children]
# masters
# workers
; localhost ansible_connection=local